### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified on Post_Cmd

### ISSUE THREAD

**Issue by dmac707** [AstunTechnology/Loader#23]
Hello Astun,

I am trying to load an extract from Addressbase Premium into my local PostGis but have hit a wall. I ran it in debug mode and it appears to be crashing out at the post_command stage. It processes the GML and creates a .sql file in the out folder (although this is just says BEGIN COMMIT 5 times). The file paths in the post command look wrong so I hard coded them in the config file but to no avail. I am running loader from Astun's Portable GIS. The debug output is below. Any thoughts? 

J:\usbgis\apps\loader\python>python loader.py loaderABP.config debug=true
Config: {'tmp_dir': 'J:\\AddressBaseGML\\Temp', 'out_dir': 'J:\\AddressBaseGML\\
Out', 'gfs_file': '../gfs/addressbase_premium_postgres.gfs', 'ogr_cmd': 'ogr2ogr
 --config PG_LIST_ALL_TABLES YES --config PG_USE_COPY YES --config GML_EXPOSE_FI
D NO -skipfailures -lco spatial_index=off -lco create_table=off -lco schema=addr
essbase_premium -lco create_schema=off -f PGDump $output_dir/$base_file_name.sql
 $file_path', 'post_cmd': "sh -c 'PGPASSWORD=Badreligion@01 psql -h localhost -U
 postgres -d LocalPostGis -f $output_dir/$base_file_name.sql && rm $output_dir/$
base_file_name.sql'", 'debug': 'true', 'src_dir': 'J:\\AddressBaseGML\\In', 'pre
p_cmd': 'python prepgml4ogr.py $file_path prep_osgml.prep_addressbase_premium'}
Processing: J:\AddressBaseGML\In\0001571031_001_002.gml
Prepared file: J:\AddressBaseGML\Temp\tmpoxtzab\0001571031_001_002
Prep command: python prepgml4ogr.py J:\AddressBaseGML\In\0001571031_001_002.gml
prep_osgml.prep_addressbase_premium
Loading: J:\AddressBaseGML\In\0001571031_001_002.gml
OGR command: ogr2ogr --config PG_LIST_ALL_TABLES YES --config PG_USE_COPY YES --
config GML_EXPOSE_FID NO -skipfailures -lco spatial_index=off -lco create_table=
off -lco schema=addressbase_premium -lco create_schema=off -f PGDump J:\AddressB
aseGML\Out/0001571031_001_002.sql J:\AddressBaseGML\Temp\tmpoxtzab\0001571031_00
1_002
Post command: sh -c PGPASSWORD=********************** psql -h localhost -U postgres -d L
ocalPostGis -f J:AddressBaseGMLOut/0001571031_001_002.sql && rm J:AddressBaseGML
Out/0001571031_001_002.sql
Traceback (most recent call last):
  File "loader.py", line 192, in <module>
    main()
  File "loader.py", line 181, in main
    loader.run(config)
  File "loader.py", line 58, in run
    self.load()
  File "loader.py", line 107, in load
    self.load_file(root, name)
  File "loader.py", line 152, in load_file
    subprocess.call(post_args, stderr=sys.stderr)
  File "J:\usbgis\apps\python27\App\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "J:\usbgis\apps\python27\App\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "J:\usbgis\apps\python27\App\lib\subprocess.py", line 957, in _execute_ch
ild
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by walkermatt** [comment]
@dmac707 I think the issue here is that forward slashed in the `post_cmd` are being interpreted by  as switches (options). You're going to have to experiment with the path seperator. Maybe try using `\\` as the path seperator for all paths in which case your `prep_cmd` would probably look like this:

`cmd.exe /c 'set PGPASSWORD=***************** psql -h localhost -U postgres -d LocalPostGis -f $output_dir\\$base_file_name.sql && del $output_dir\\$base_file_name.sql'`

I'm happy to play along if you are but as I said before if you only have a handful of files it's probably worth just using the more convential `PostgreSQL` OGR driver which doesn't require a `post_cmd` as it loads directly into PostgreSQL.

**Comment by dmac707** [comment]
@walkermatt I have loaded the data using ``PostgreSQL`` option. I am happy to lay this issue to rest.

**Comment by walkermatt** [comment]
@dmac707 thanks for letting me know, glad you got the data loaded :smile:
