### ISSUE TITLE
MultiLineString - LineString

### ISSUE THREAD

**Issue by TimJMartin** [AstunTechnology/Loader#25]
Hi Matt

Having done some tests over the last few days I believe the geometry definition for the topographicline table should be LINESTRING

https://github.com/AstunTechnology/Loader/blob/master/extras/ordnancesurvey/osmm/topo/pgdump/create-tables.sql

When I used your version of create-tables.sql, loader through an error

Cheers

Tim

**Comment by walkermatt** [comment]
Leaving as `MULTILINESTRING` following discussion with @TimJMartin
