### ISSUE TITLE
Incomplete grade separation data

### ISSUE THREAD

**Issue by ibennett** [AstunTechnology/Loader#26]
When using the latest gfs file for ITN into PostGreSQL I was expecting to see the values for fid='osgb4000000023329254' it should return the following <osgb:directedNode orientation='-' gradeSeparation='1' xlink:href='#osgb4000000023150963'/>

However in the data base only the directed node orientation is popoluated with 0,1 and the gradeseparation and href values are both blank.

**Comment by walkermatt** [comment]
@ibennett that's interesting I'm getting the following record in the `roadlink` table which includes all `directednode` values that are present in the source data:

    -[ RECORD 1 ]-------------------+-------------------------------------------------------------------------------------------
    ogc_fid                         | 28207
    wkb_geometry                    | 0102000020346C000002000000AC1C5AE46BBC1D41713D0AD74B5B0041C3F528DC52BD1D41A245B6F34C5D0041
    fid                             | osgb4000000023329254
    version                         | 7
    versiondate                     | 2011-09-05
    changedate                      | {2003-10-07,2003-10-07,2009-12-23,2011-08-17}
    reasonforchange                 | {Modified,New,Modified,Modified}
    descriptivegroup                | Road Topology
    descriptiveterm                 | A Road
    natureofroad                    | Dual Carriageway
    length                          | 86.3
    directednode_href               | {#osgb4000000023150963,#osgb4000000023838736}
    directednode_orientation        | {-,+}
    directednode_gradeseparation    | {1}
    referencetotopographicarea_href | {#osgb1000002703058887}
    theme                           | Road Network
    filename                        | 1566765-000012-30.gz


I'm using Python 2.7.6, GDAL 1.11.0 and PostgreSQL 9.3.5 with PostGIS 2.1.

I'd be interested in what versions you are using and in seeing the prepared data which is output during loading to the `tmp_dir` you've specified. Could you loading the file containing that `roadlink` in debug mode and then post the GML for just that feature? I get the following:

```xml
<RoadLink fid="osgb4000000023329254">
    <version>7</version>
    <versionDate>2011-09-05</versionDate>
    <theme>Road Network</theme>
    <changeHistory>
        <changeDate>2003-10-07</changeDate>
        <reasonForChange>Modified</reasonForChange>
    </changeHistory>
    <changeHistory>
        <changeDate>2003-10-07</changeDate>
        <reasonForChange>New</reasonForChange>
    </changeHistory>
    <changeHistory>
        <changeDate>2009-12-23</changeDate>
        <reasonForChange>Modified</reasonForChange>
    </changeHistory>
    <changeHistory>
        <changeDate>2011-08-17</changeDate>
        <reasonForChange>Modified</reasonForChange>
    </changeHistory>
    <descriptiveGroup>Road Topology</descriptiveGroup>
    <descriptiveTerm>A Road</descriptiveTerm>
    <natureOfRoad>Dual Carriageway</natureOfRoad>
    <length>86.30</length>
    <polyline>
        <LineString srsName="EPSG:27700">
            <coordinates>487194.973,133993.480 487252.715,134057.619</coordinates>
        </LineString>
    </polyline>
    <directedNode gradeSeparation="1" href="#osgb4000000023150963" orientation="-">
        <directedNode_gradeSeparation>1</directedNode_gradeSeparation>
        <directedNode_href>#osgb4000000023150963</directedNode_href>
        <directedNode_orientation>-</directedNode_orientation>
    </directedNode>
    <directedNode href="#osgb4000000023838736" orientation="+">
        <directedNode_href>#osgb4000000023838736</directedNode_href>
        <directedNode_orientation>+</directedNode_orientation>
    </directedNode>
    <referenceToTopographicArea href="#osgb1000002703058887">
        <referenceToTopographicArea_href>#osgb1000002703058887</referenceToTopographicArea_href>
    </referenceToTopographicArea>
    <fid>osgb4000000023329254</fid>
    <filename>1566765-000012-30.gz</filename>
</RoadLink>
```

Looking into this issue has highlighted a related issue which I'll create a seperate issue for: #27.

**Comment by walkermatt** [comment]
@ibennett Hi, can you confirm if this is now resolved and can be closed?
