### ISSUE TITLE
Update data for OSMM (like VML)

### ISSUE THREAD

**Issue by ramotswa** [AstunTechnology/Loader#32]
Presumably the way VML is updated would work for OSMM too? Would it just be the case of updating the sql scripts to match the OSMM tables?

**Comment by walkermatt** [comment]
Unfortunatly not, updates to VML are supplied at the tile level meaning that we simply load the new data then replace all features in the current holding that belong to the superseeded tiles with the new. 

OSMM is supplied as change only updates (COU) which is a little more complicated as you have some new features, some updated and some departed. The logic is not that involved but I'm yet to implement it. I've spoken to a few people about implementing the logic in Postgres as it's generally our destination but also in SQLite which would allow users to maintain a holding in SQLite then export the current holding to other file based formats if required.

**Comment by ramotswa** [comment]
Hi, just FYI - I just got a refresh from MasterMap - and they are now delivering them in 5k gml files (i.e. one gml file per 5k square.) Personally very handy as I can load specific areas to test. And might make COU a bit easier..
