### ISSUE TITLE
Verification of loaded data

### ISSUE THREAD

**Issue by ramotswa** [AstunTechnology/Loader#33]
Hey @walkermatt , 

I was wondering - how do you verify that all the data you have asked to be loaded has actually been loaded (with regards to OSMM topo)? Do you go by row count somehow? 
I am just playing with the idea of creating some sort of verification strategy which involves extracting all the FIDS from the .gz files from the OS, and then checking if they exist in the database. 

Coming up against the obvious problem that I will be asking (at best) the database to do 108 million lookups on 108 million rows! ! 

It would be quite useful to insert the FIDS into a separate table on load so that this can be done a bit more efficiently, but wondering if you have any insight.

Cheers,

Toby

**Comment by walkermatt** [comment]
Hi Toby,

I usually count each feature type (table) per source file. I use SQL create a table containing the count of features in each database table grouped on the `filename` column. I then use `ogrinfo` to get a count for each feature type in each source file; which I then load as a table in the database so I can perform a join to identify any differences. The `filename` column makes it easy to delete and reload one or more source files if needed.

**Comment by ramotswa** [comment]
Hi Matt,
The filename column is indeed very handy - thanks very much for pointing that out. I've written a quick python script to count the features in each gz file and turn them into a sql insert script which I can now compare with db count.
