### ISSUE TITLE
openmap.gfs shortened name values cause issues with OS Stylesheets

### ISSUE THREAD

**Issue by JamesGardiner** [AstunTechnology/Loader#37]
Hi, I've been using the Loader to get OS OpenMap - Local data into a PostGIS extended database. All works fine, but when applying the [OS Stylesheets] (http://www.ordnancesurvey.co.uk/business-and-government/help-and-support/products/os-open-map-local.html) in QGIS, certain styles fail to be applied. 

The issue relates to shortened <PropertyDefn> <name> values in the openmap.gfs file, such as distName rather than distinctiveName and classifica rather than classification. Altering these before loading results in the correct styles being applied.

Thanks,

James

**Comment by walkermatt** [comment]
Hi James,

I think the reason is that only the Shape style files where available when I last looked at OS OpenMap during the beta period hence the truncated column names. If you have an updated gfs could you submit a pull request?

Cheers,

Matt.
