### ISSUE TITLE
OSMM create_tables script issues

### ISSUE THREAD

**Issue by ramotswa** [AstunTechnology/Loader#39]
Hi Matt,

Kind of just FYI.

Been using the loader for OSMM to use with Geoserver - I have found that using your existing scripts to create the tables (Loader/extras/ordnancesurvey/osmm/topo/pgdump/create-tables.sql) has issues because of the "character varying []" for various fields. Geoserver (2.6.1) doesn't seem to like these so doesn't bring them through (confirmed by the geoserver mail list), which is a shame as they are useful for styling. I'm changing them to 'character varying' for now.

**Comment by walkermatt** [comment]
What I've generally done is either to create views in the database or [GeoServer SQL View layers](http://docs.geoserver.org/stable/en/user/data/database/sqlview.html) which only include the required columns and joins the array fields into plain character columns:

    SELECT
    ...
    array_to_string(descriptivegroup, ', ') as descriptivegroup,
    array_to_string(descriptiveterm, ', ') as descriptiveterm
    ...
    FROM osmm_topo.topographicarea;

**Comment by ramotswa** [comment]
Thanks Matt.
