### ISSUE TITLE
PGDump and USE COPY

### ISSUE THREAD

**Issue by ramotswa** [AstunTechnology/Loader#44]
Hi Matt,
Not an issue more a query if I may. 

I don't know when - but the ogr2ogr command has changed since I grabbed the repo initially. You are no longer using the -f PGDump and PG_USE_COPY options in the latest ones. I was just wondering why you changed that? From the note in your initial .config file it sounded like the performance of copy would be better than insert.. has that changed with more recent versions of postgres?

Thanks

Toby

**Comment by walkermatt** [comment]
Hi Toby,

Are you maybe thinking of the config under [extras/ordnancesurvey/osmm/topo/pgdump](https://github.com/AstunTechnology/Loader/tree/master/extras/ordnancesurvey/osmm/topo/pgdump)?

Cheers,

Matt.

**Comment by ramotswa** [comment]
Hmmm. maybe. 
As you were. :) 
Toby
