### ISSUE TITLE
Addressbase Premium - Loading values in degrees

### ISSUE THREAD

**Issue by GeoWill** [AstunTechnology/Loader#49]
Hi there, 

I'm loading Addressbase premium into postGIS. The loader seems to be working fine, and I can view the data in QGIS. 
However if I query the wkb_geometry columns with the ST_AsEWKT() function I get returns such as: 
SRID=27700;POINT(-4.223... 55.859...)
This appears to be values in degrees rather than metres as I'd expect for British National Grid. 
I assume these values are in EPSG:4258 as that is the other ABP SRID, but I'm wanted to check before just resetting the SRIDs and doing a conversion.

I've tried to have a bit of a poke about, and wondered if it was to do with the prep_osgml.prep_addressbase class. The other classes inherit from the generic prep_osgml.prep_osgml class, but prep_addressbase doesn't. There doesn't appear to be an equivalent method to the _set_srs in the prep_addressbase class.

However this may be way off, as I'm very new to parsing gml and don't fully understand which bits ogr2ogr takes care of vs loader.

Many thanks for all your work on this, I hope to be able to contribute eventually!
Will

**Comment by walkermatt** [comment]
That does look odd, the SRS is set via [`gfs/addressbase_premium_postgres.gfs`](https://github.com/AstunTechnology/Loader/blob/master/gfs/addressbase_premium_postgres.gfs) which specifies EPSG:27700. Is the data displaying in EPSG:27700 within QGIS and what does `geometry_columns` say in PostGIS?

**Comment by GeoWill** [comment]
Thanks for the quick response. 
When to mention the `geometry_columns` is that the 'wkb_geometry' column? data type for those is (Point,27700).
In QGIS the CRS is defined as 27700 in the bottom right corner, and in the layer properties. However int he Coordinate box it is showing degrees as well.
I used 'gfs/addressbase_premium_postgres.gfs' in the config file.

**Comment by GeoWill** [comment]
Sorry, not paying attention re. `geography_columns`.
`geography_columns` vies is empty I think.
`geometry_columns` has SRID integer set to 27700.

**Comment by walkermatt** [comment]
Everything seems to suggest that the SRS is correct, do the points appear in the correct location relative to some other reference data that's in BNG when displayed in QGIS? Could you try inspecting the geometry in PostGIS with [ST_AsGML](http://postgis.net/docs/manual-2.3/ST_AsGML.html) or ST_X/ ST_Y?

**Comment by GeoWill** [comment]
So it seems that the SRS is 27700, but the co-ordinates stored are the degrees values, but it is treating them as metres.
* In QGIS:
  * ESPG is 27700
  * Addressbase points are at away down by the origin i.e. the x/y values are being interpreted as if they're in metres
* ST_AsGML
  * `<gml:Point srsName="EPSG:27700"><gml:coordinates>-4.762053,55.944662000000001</gml:coordinates></gml:Point>`
* ST_X and ST_Y
  * Gives similar values that look like degrees.
  * e.g. `-4.767...` and `55.941...`

**Comment by GeoWill** [comment]
Quick update.
I ran:
`SELECT UpdateGeometrySRID('addressbase_premium','basiclandpropertyunit','wkb_geometry',4258);`
And then reran my queries with `ST_Transform(geom,27700)` and am getting usable results - I was after `ST_DWithin` and `ST_Distance` and metre level precision not needed. 
However it would still be nice to resolve why the coordinate values and the SRS were mixed up.

**Comment by walkermatt** [comment]
I'm planning on looking at this and #50 next week.

**Comment by walkermatt** [comment]
I've been able to reproduce using the latest sample data. I think the issue was that OGR uses the last geometry it encounters for a feature unless it's told explicitly which element to use. The AddressBase GML now comes with two geometries, one in British National Grid, the other in WGS84. I've updated the `.gfs` files to specify the British National Grid geometry and I'm now seeing points in BNG at the correct location.

Once you've updated your copy of Loader you should be able to test.

**Comment by GeoWill** [comment]
Great, thank you!
