### ISSUE TITLE
AddressBase Premium classification format

### ISSUE THREAD

**Issue by thomparker** [AstunTechnology/Loader#50]
Hi Matt,

Loading AddressBase generates a lot of warnings about Classification.schemeVersion being the wrong format. It appears to be supplied in decimal format eg "1.0" Therefore should the gfs file be changed to:

```
<PropertyDefn>
            <Name>schemeVersion</Name>
            <ElementPath>schemeVersion</ElementPath>
            <Type>Real</Type>
</PropertyDefn>
```

to accommodate this?

Thanks
Tom

**Comment by walkermatt** [comment]
Thanks Tom. I've been able to reproduce, fixed in 3af4d0c39852333dbb3c5623814f79b2f0f2057a.
