### ISSUE TITLE
gml to gpkg out file name issue?

### ISSUE THREAD

**Issue by samfranklin** [AstunTechnology/Loader#62]
Hi. Quick query on using loader to write from OS MM Topo (GML) to a geopackage, specifically using the out_dir variable.

I'm on:
ubuntu=16.04
python=2.7.12 (default, Dec  4 2017, 14:50:18)
gdal=2.1.3
lxml=4.2.4
loader=pulled down yesterday (2018-08-16), so assume latest?

Here's my config:
```
file_path=/vagrant/tests/data/gml_gpkg/in/mm-topo-sample.gml
out_dir=/vagrant/tests/data/gml_gpkg/out/mm-topo-sample.gpkg
tmp_dir=/tmp
ogr_cmd=ogr2ogr -f "GPKG" -append -skipfailures $out_dir $file_path
prep_cmd=python prepgml4ogr.py $file_path prep_osgml.prep_osmm_topo_qgis
gfs_file=../gfs/osmm_topo_shape_qgis.gfs
debug=True
```

I see the warning (see last line of the code block) when I run this config
```
user@host:~$ python loader.py loader.config
Config: {'tmp_dir': '/tmp', 'out_dir': '/vagrant/tests/data/gml_gpkg/out/mm-topo-sample.gpkg', 'ogr_cmd': 'ogr2ogr -f "GPKG" -append -skipfailures $out_dir $file_path', 'gfs_file': '../gfs/osmm_topo_shape_qgis.gfs', 'debug': 'True', 'src_dir': '/vagrant/tests/data/gml_gpkg/in', 'prep_cmd': 'python prepgml4ogr.py $file_path prep_osgml.prep_osmm_topo_qgis', 'file_path': '/vagrant/tests/data/gml_gpkg/in/mm-topo-sample.gml'}
Processing: /vagrant/tests/data/gml_gpkg/in/mm-topo-sample.gml
Prepared file: /tmp/tmpXalKVZ/mm-topo-sample
Prep command: python prepgml4ogr.py /vagrant/tests/data/gml_gpkg/in/mm-topo-sample.gml prep_osgml.prep_osmm_topo_qgis
Loading: /vagrant/tests/data/gml_gpkg/in/mm-topo-sample.gml
OGR command: ogr2ogr -f GPKG -append -skipfailures $out_dir /tmp/tmpXalKVZ/mm-topo-sample
Warning 1: The '' extension is not allowed by the GPKG specification, which may cause compatibility problems
```

It's a simple issue, the geopackage gets written as this specific filename `.../loader/python/$out_dir` when `/vagrant/tests/data/gml_gpkg/out/mm-topo-sample.gpkg` is in the config.

I've tried using a directory only instead of a full path to a .gpkg. The result is the same.
I know I can manually rename the "$out_dir" to ".../mm-topo-sample.gpkg" but I thought I'd flag this.

Am I doing something wrong, or is this a bug with writing to geopackages?

Thanks guys in advance guys.

**Comment by walkermatt** [comment]
The issue you're getting using `$out_dir` in the `ogr_cmd` is easy to fix but a bit annoying! For no good reason I can remember you need to use `$output_dir` and not `$out_dir`. I think we should allow both in future as I had to look it up in the source code.

I think `Warning 1: The '' extension is not allowed by the GPKG specification, which may cause compatibility problems` is a separate issue. To the `$out_dir` issue.

If you're loading schema v9 OSMM Topo then you probably want to use `prep_osgml.prep_osmm_topo` and `gfs/osmm_topo_postgres.gfs` which include the `style_code` and associated attributes which are compatible with the v9 OS stylesheets in QGIS, GeoServer etc. You will probably get a bunch of warnings regarding the list fields which you can probably overcome by creating a  copy of `gfs/osmm_topo_postgres.gfs` as `gfs/osmm_topo_gpkg.gfs` replacing `StringList` with `String`. If it works out I'd be happy to consider a pull request.

**Comment by samfranklin** [comment]
Hey @walkermatt - I those suggestions worked, thanks!
Ooh Pull Request ,that's exciting! So just to confirm (for the uninitiated), the only file that should change in my pull request is the new `gfs/osmm_topo_gpkg.gfs` that now includes the `string` tag, correct?

**Comment by walkermatt** [comment]
> Ooh Pull Request ,that's exciting! So just to confirm (for the uninitiated), the only file that should change in my pull request is the new gfs/osmm_topo_gpkg.gfs that now includes the string tag, correct?

That sounds good. An OSMM Topo to GPKG example on the [configuration examples page on the wiki](https://github.com/AstunTechnology/Loader/wiki/Configuration-examples) would also be great.

BTW it might take me a while to respond as I'm on holiday at the moment :icecream:
