### ISSUE TITLE
Add license header text to all files in "extras" folder

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/Loader#63]
Loader. Copyright (c) 2018 Astun Technology Ltd. (http://astuntechnology.com)
Licensed under [MIT License](https://github.com/AstunTechnology/Loader/blob/headers/LICENSE.txt).

**Comment by walkermatt** [comment]
Just considering if the year is necessary and I think we should drop it.

I never knew that the official purpose of including a year in a copyright statement is to assert when the work was originally released (see [this stackoverflow post](https://stackoverflow.com/a/2391555/526860)).

With that in mind I'd propose we use:

```
Loader. Copyright (c) Astun Technology Ltd. (http://astuntechnology.com).
Licensed under [MIT License](https://git.io/fAxH0).
```

The git.io URL points to https://github.com/AstunTechnology/Loader/blob/master/LICENSE.txt
