### ISSUE TITLE
Attempting to load OSVML from GZ fails with a parsing error on copyright symbol

### ISSUE THREAD

**Issue by rpaliwoda** [AstunTechnology/Loader#66]
I'm attempting to load the latest release (2019/03/20 - though this issue also happens with older data) of OS VML from GZ format. For every file, it fails after loading with 'ERROR 1: XML parsing of GML file failed : not well-formed (invalid token) at line 1, column 681'; in this case, this was where the character © was used in the initial description of the data at the start of every file.

Edit: this is using Python 3 under Windows 10

Processing: I:\Processing\DIP-13204\Data\HY20NE.gz
Loading: I:\Processing\DIP-13204\Data\HY20NE.gz
ERROR 1: XML parsing of GML file failed : not well-formed (invalid token) at line 1, column 681

**Comment by walkermatt** [comment]
@coastalrocket have you encountered this issue before? We regularly load national cover of VML.

**Comment by rpaliwoda** [comment]
I'm also getting similar invalid token errors from the OS MasterMap Highways Road data, though these will be harder to find in the files as they're happening further in. One failed at line 499845, for example.

**Comment by walkermatt** [comment]
Are you loading official OS supplied data or data from a reseller or 3rd party?

**Comment by rpaliwoda** [comment]
These are official releases of data supplied directly from the OS; the only other thing that's been done with the files is copying them off the media they arrived on.

**Comment by walkermatt** [comment]
Could you share a VML gz that's failing with me? We are an OS Partner so licensing shouldn't be an issue. Can you email it to mattwalker at astuntechnology.com and I'll take a look 👍

**Comment by walkermatt** [comment]
I've just tried loading sample file you provided and it loaded successfully. Can you updating your configuration file to specify `debug=True`, this will avoid the prepared file created by Loader being deleted following the run. Can you then email me the prepared file so I can check it's encoding and content.

**Comment by walkermatt** [comment]
It looks as though the prepared file created by Loader is in latin1 not UTF-8 which is likely to be the problem. Can you try setting the `PYTHONIOENCODING` environment variable to `utf-8` in the command prompt prior to running Loader. On Windows you'd execute:

    set PYTHONIOENCODING=utf-8

prior to running Loader.

Regardless of whether this works can you please send me the new prepared file as before.

**Comment by walkermatt** [comment]
@rpaliwoda good to hear that setting the environment variable seems to of done the trick. I can see from the prepared file that you provide via email that it's now encoded at UTF-8 which is what we're expecting.

The next time I look at making changes to Loader I'll see about ensuring the prepared file is written as UTF-8 by default avoiding the need for the environment variable in future.
